/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicEventsRouteImport } from './routes/_public/events'
import { Route as PublicDataRouteImport } from './routes/_public/data'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as PublicRequestsRouteRouteImport } from './routes/_public/requests/route'
import { Route as PublicFundAProjectRouteRouteImport } from './routes/_public/fund-a-project/route'
import { Route as PublicRequestsIndexRouteImport } from './routes/_public/requests/index'
import { Route as PublicFundAProjectIndexRouteImport } from './routes/_public/fund-a-project/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PublicRequestsIdRouteImport } from './routes/_public/requests/$id'
import { Route as PublicFundAProjectIdRouteImport } from './routes/_public/fund-a-project/$id'
import { Route as PublicEventsIdRouteImport } from './routes/_public/events.$id'
import { Route as AuthenticatedUDashboardRouteImport } from './routes/_authenticated/u/dashboard'
import { Route as AuthenticatedUUIdSettingsRouteImport } from './routes/_authenticated/u/$uId/settings'
import { Route as AuthenticatedUUIdProfileRouteImport } from './routes/_authenticated/u/$uId/profile'
import { Route as AuthenticatedUUIdFundmeRouteImport } from './routes/_authenticated/u/$uId/fundme'
import { Route as AuthenticatedOrgsOrgIdSettingsRouteImport } from './routes/_authenticated/orgs/$orgId/settings'
import { Route as AuthenticatedOrgsOrgIdProfileRouteImport } from './routes/_authenticated/orgs/$orgId/profile'
import { Route as AuthenticatedOrgsOrgIdMembersRouteImport } from './routes/_authenticated/orgs/$orgId/members'
import { Route as AuthenticatedOrgsOrgIdEventsRouteImport } from './routes/_authenticated/orgs/$orgId/events'
import { Route as AuthenticatedOrgsOrgIdDashboardRouteImport } from './routes/_authenticated/orgs/$orgId/dashboard'
import { Route as AuthenticatedUUIdTagsIndexRouteImport } from './routes/_authenticated/u/$uId/tags/index'
import { Route as AuthenticatedUUIdProfileIndexRouteImport } from './routes/_authenticated/u/$uId/profile/index'
import { Route as AuthenticatedUUIdRequestsNewRouteImport } from './routes/_authenticated/u/$uId/requests/new'
import { Route as AuthenticatedUUIdProfileNewRouteImport } from './routes/_authenticated/u/$uId/profile/new'
import { Route as AuthenticatedUUIdProfileEditRouteImport } from './routes/_authenticated/u/$uId/profile/edit'
import { Route as AuthenticatedUUIdFundAProjectNewRouteImport } from './routes/_authenticated/u/$uId/fund-a-project/new'
import { Route as AuthenticatedUUIdRequestsRequestIdEditRouteImport } from './routes/_authenticated/u/$uId/requests/$requestId/edit'
import { Route as AuthenticatedUUIdFundAProjectFundAProjectIdEditRouteImport } from './routes/_authenticated/u/$uId/fund-a-project/$fundAProjectId/edit'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicEventsRoute = PublicEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDataRoute = PublicDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => PublicRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRequestsRouteRoute = PublicRequestsRouteRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFundAProjectRouteRoute = PublicFundAProjectRouteRouteImport.update({
  id: '/fund-a-project',
  path: '/fund-a-project',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRequestsIndexRoute = PublicRequestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRequestsRouteRoute,
} as any)
const PublicFundAProjectIndexRoute = PublicFundAProjectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicFundAProjectRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRequestsIdRoute = PublicRequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PublicRequestsRouteRoute,
} as any)
const PublicFundAProjectIdRoute = PublicFundAProjectIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PublicFundAProjectRouteRoute,
} as any)
const PublicEventsIdRoute = PublicEventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PublicEventsRoute,
} as any)
const AuthenticatedUDashboardRoute = AuthenticatedUDashboardRouteImport.update({
  id: '/u/dashboard',
  path: '/u/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUUIdSettingsRoute =
  AuthenticatedUUIdSettingsRouteImport.update({
    id: '/u/$uId/settings',
    path: '/u/$uId/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUUIdProfileRoute =
  AuthenticatedUUIdProfileRouteImport.update({
    id: '/u/$uId/profile',
    path: '/u/$uId/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUUIdFundmeRoute = AuthenticatedUUIdFundmeRouteImport.update({
  id: '/u/$uId/fundme',
  path: '/u/$uId/fundme',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrgsOrgIdSettingsRoute =
  AuthenticatedOrgsOrgIdSettingsRouteImport.update({
    id: '/orgs/$orgId/settings',
    path: '/orgs/$orgId/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrgsOrgIdProfileRoute =
  AuthenticatedOrgsOrgIdProfileRouteImport.update({
    id: '/orgs/$orgId/profile',
    path: '/orgs/$orgId/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrgsOrgIdMembersRoute =
  AuthenticatedOrgsOrgIdMembersRouteImport.update({
    id: '/orgs/$orgId/members',
    path: '/orgs/$orgId/members',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrgsOrgIdEventsRoute =
  AuthenticatedOrgsOrgIdEventsRouteImport.update({
    id: '/orgs/$orgId/events',
    path: '/orgs/$orgId/events',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrgsOrgIdDashboardRoute =
  AuthenticatedOrgsOrgIdDashboardRouteImport.update({
    id: '/orgs/$orgId/dashboard',
    path: '/orgs/$orgId/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUUIdTagsIndexRoute =
  AuthenticatedUUIdTagsIndexRouteImport.update({
    id: '/u/$uId/tags/',
    path: '/u/$uId/tags/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUUIdProfileIndexRoute =
  AuthenticatedUUIdProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedUUIdProfileRoute,
  } as any)
const AuthenticatedUUIdRequestsNewRoute =
  AuthenticatedUUIdRequestsNewRouteImport.update({
    id: '/u/$uId/requests/new',
    path: '/u/$uId/requests/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUUIdProfileNewRoute =
  AuthenticatedUUIdProfileNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedUUIdProfileRoute,
  } as any)
const AuthenticatedUUIdProfileEditRoute =
  AuthenticatedUUIdProfileEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedUUIdProfileRoute,
  } as any)
const AuthenticatedUUIdFundAProjectNewRoute =
  AuthenticatedUUIdFundAProjectNewRouteImport.update({
    id: '/u/$uId/fund-a-project/new',
    path: '/u/$uId/fund-a-project/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUUIdRequestsRequestIdEditRoute =
  AuthenticatedUUIdRequestsRequestIdEditRouteImport.update({
    id: '/u/$uId/requests/$requestId/edit',
    path: '/u/$uId/requests/$requestId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUUIdFundAProjectFundAProjectIdEditRoute =
  AuthenticatedUUIdFundAProjectFundAProjectIdEditRouteImport.update({
    id: '/u/$uId/fund-a-project/$fundAProjectId/edit',
    path: '/u/$uId/fund-a-project/$fundAProjectId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/fund-a-project': typeof PublicFundAProjectRouteRouteWithChildren
  '/requests': typeof PublicRequestsRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/data': typeof PublicDataRoute
  '/events': typeof PublicEventsRouteWithChildren
  '/': typeof PublicIndexRoute
  '/u/dashboard': typeof AuthenticatedUDashboardRoute
  '/events/$id': typeof PublicEventsIdRoute
  '/fund-a-project/$id': typeof PublicFundAProjectIdRoute
  '/requests/$id': typeof PublicRequestsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/fund-a-project/': typeof PublicFundAProjectIndexRoute
  '/requests/': typeof PublicRequestsIndexRoute
  '/orgs/$orgId/dashboard': typeof AuthenticatedOrgsOrgIdDashboardRoute
  '/orgs/$orgId/events': typeof AuthenticatedOrgsOrgIdEventsRoute
  '/orgs/$orgId/members': typeof AuthenticatedOrgsOrgIdMembersRoute
  '/orgs/$orgId/profile': typeof AuthenticatedOrgsOrgIdProfileRoute
  '/orgs/$orgId/settings': typeof AuthenticatedOrgsOrgIdSettingsRoute
  '/u/$uId/fundme': typeof AuthenticatedUUIdFundmeRoute
  '/u/$uId/profile': typeof AuthenticatedUUIdProfileRouteWithChildren
  '/u/$uId/settings': typeof AuthenticatedUUIdSettingsRoute
  '/u/$uId/fund-a-project/new': typeof AuthenticatedUUIdFundAProjectNewRoute
  '/u/$uId/profile/edit': typeof AuthenticatedUUIdProfileEditRoute
  '/u/$uId/profile/new': typeof AuthenticatedUUIdProfileNewRoute
  '/u/$uId/requests/new': typeof AuthenticatedUUIdRequestsNewRoute
  '/u/$uId/profile/': typeof AuthenticatedUUIdProfileIndexRoute
  '/u/$uId/tags': typeof AuthenticatedUUIdTagsIndexRoute
  '/u/$uId/fund-a-project/$fundAProjectId/edit': typeof AuthenticatedUUIdFundAProjectFundAProjectIdEditRoute
  '/u/$uId/requests/$requestId/edit': typeof AuthenticatedUUIdRequestsRequestIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/data': typeof PublicDataRoute
  '/events': typeof PublicEventsRouteWithChildren
  '/': typeof PublicIndexRoute
  '/u/dashboard': typeof AuthenticatedUDashboardRoute
  '/events/$id': typeof PublicEventsIdRoute
  '/fund-a-project/$id': typeof PublicFundAProjectIdRoute
  '/requests/$id': typeof PublicRequestsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/fund-a-project': typeof PublicFundAProjectIndexRoute
  '/requests': typeof PublicRequestsIndexRoute
  '/orgs/$orgId/dashboard': typeof AuthenticatedOrgsOrgIdDashboardRoute
  '/orgs/$orgId/events': typeof AuthenticatedOrgsOrgIdEventsRoute
  '/orgs/$orgId/members': typeof AuthenticatedOrgsOrgIdMembersRoute
  '/orgs/$orgId/profile': typeof AuthenticatedOrgsOrgIdProfileRoute
  '/orgs/$orgId/settings': typeof AuthenticatedOrgsOrgIdSettingsRoute
  '/u/$uId/fundme': typeof AuthenticatedUUIdFundmeRoute
  '/u/$uId/settings': typeof AuthenticatedUUIdSettingsRoute
  '/u/$uId/fund-a-project/new': typeof AuthenticatedUUIdFundAProjectNewRoute
  '/u/$uId/profile/edit': typeof AuthenticatedUUIdProfileEditRoute
  '/u/$uId/profile/new': typeof AuthenticatedUUIdProfileNewRoute
  '/u/$uId/requests/new': typeof AuthenticatedUUIdRequestsNewRoute
  '/u/$uId/profile': typeof AuthenticatedUUIdProfileIndexRoute
  '/u/$uId/tags': typeof AuthenticatedUUIdTagsIndexRoute
  '/u/$uId/fund-a-project/$fundAProjectId/edit': typeof AuthenticatedUUIdFundAProjectFundAProjectIdEditRoute
  '/u/$uId/requests/$requestId/edit': typeof AuthenticatedUUIdRequestsRequestIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_public/fund-a-project': typeof PublicFundAProjectRouteRouteWithChildren
  '/_public/requests': typeof PublicRequestsRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/_public/data': typeof PublicDataRoute
  '/_public/events': typeof PublicEventsRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/_authenticated/u/dashboard': typeof AuthenticatedUDashboardRoute
  '/_public/events/$id': typeof PublicEventsIdRoute
  '/_public/fund-a-project/$id': typeof PublicFundAProjectIdRoute
  '/_public/requests/$id': typeof PublicRequestsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_public/fund-a-project/': typeof PublicFundAProjectIndexRoute
  '/_public/requests/': typeof PublicRequestsIndexRoute
  '/_authenticated/orgs/$orgId/dashboard': typeof AuthenticatedOrgsOrgIdDashboardRoute
  '/_authenticated/orgs/$orgId/events': typeof AuthenticatedOrgsOrgIdEventsRoute
  '/_authenticated/orgs/$orgId/members': typeof AuthenticatedOrgsOrgIdMembersRoute
  '/_authenticated/orgs/$orgId/profile': typeof AuthenticatedOrgsOrgIdProfileRoute
  '/_authenticated/orgs/$orgId/settings': typeof AuthenticatedOrgsOrgIdSettingsRoute
  '/_authenticated/u/$uId/fundme': typeof AuthenticatedUUIdFundmeRoute
  '/_authenticated/u/$uId/profile': typeof AuthenticatedUUIdProfileRouteWithChildren
  '/_authenticated/u/$uId/settings': typeof AuthenticatedUUIdSettingsRoute
  '/_authenticated/u/$uId/fund-a-project/new': typeof AuthenticatedUUIdFundAProjectNewRoute
  '/_authenticated/u/$uId/profile/edit': typeof AuthenticatedUUIdProfileEditRoute
  '/_authenticated/u/$uId/profile/new': typeof AuthenticatedUUIdProfileNewRoute
  '/_authenticated/u/$uId/requests/new': typeof AuthenticatedUUIdRequestsNewRoute
  '/_authenticated/u/$uId/profile/': typeof AuthenticatedUUIdProfileIndexRoute
  '/_authenticated/u/$uId/tags/': typeof AuthenticatedUUIdTagsIndexRoute
  '/_authenticated/u/$uId/fund-a-project/$fundAProjectId/edit': typeof AuthenticatedUUIdFundAProjectFundAProjectIdEditRoute
  '/_authenticated/u/$uId/requests/$requestId/edit': typeof AuthenticatedUUIdRequestsRequestIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/fund-a-project'
    | '/requests'
    | '/login'
    | '/signup'
    | '/data'
    | '/events'
    | '/'
    | '/u/dashboard'
    | '/events/$id'
    | '/fund-a-project/$id'
    | '/requests/$id'
    | '/api/auth/$'
    | '/fund-a-project/'
    | '/requests/'
    | '/orgs/$orgId/dashboard'
    | '/orgs/$orgId/events'
    | '/orgs/$orgId/members'
    | '/orgs/$orgId/profile'
    | '/orgs/$orgId/settings'
    | '/u/$uId/fundme'
    | '/u/$uId/profile'
    | '/u/$uId/settings'
    | '/u/$uId/fund-a-project/new'
    | '/u/$uId/profile/edit'
    | '/u/$uId/profile/new'
    | '/u/$uId/requests/new'
    | '/u/$uId/profile/'
    | '/u/$uId/tags'
    | '/u/$uId/fund-a-project/$fundAProjectId/edit'
    | '/u/$uId/requests/$requestId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/data'
    | '/events'
    | '/'
    | '/u/dashboard'
    | '/events/$id'
    | '/fund-a-project/$id'
    | '/requests/$id'
    | '/api/auth/$'
    | '/fund-a-project'
    | '/requests'
    | '/orgs/$orgId/dashboard'
    | '/orgs/$orgId/events'
    | '/orgs/$orgId/members'
    | '/orgs/$orgId/profile'
    | '/orgs/$orgId/settings'
    | '/u/$uId/fundme'
    | '/u/$uId/settings'
    | '/u/$uId/fund-a-project/new'
    | '/u/$uId/profile/edit'
    | '/u/$uId/profile/new'
    | '/u/$uId/requests/new'
    | '/u/$uId/profile'
    | '/u/$uId/tags'
    | '/u/$uId/fund-a-project/$fundAProjectId/edit'
    | '/u/$uId/requests/$requestId/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/_public/fund-a-project'
    | '/_public/requests'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/_public/data'
    | '/_public/events'
    | '/_public/'
    | '/_authenticated/u/dashboard'
    | '/_public/events/$id'
    | '/_public/fund-a-project/$id'
    | '/_public/requests/$id'
    | '/api/auth/$'
    | '/_public/fund-a-project/'
    | '/_public/requests/'
    | '/_authenticated/orgs/$orgId/dashboard'
    | '/_authenticated/orgs/$orgId/events'
    | '/_authenticated/orgs/$orgId/members'
    | '/_authenticated/orgs/$orgId/profile'
    | '/_authenticated/orgs/$orgId/settings'
    | '/_authenticated/u/$uId/fundme'
    | '/_authenticated/u/$uId/profile'
    | '/_authenticated/u/$uId/settings'
    | '/_authenticated/u/$uId/fund-a-project/new'
    | '/_authenticated/u/$uId/profile/edit'
    | '/_authenticated/u/$uId/profile/new'
    | '/_authenticated/u/$uId/requests/new'
    | '/_authenticated/u/$uId/profile/'
    | '/_authenticated/u/$uId/tags/'
    | '/_authenticated/u/$uId/fund-a-project/$fundAProjectId/edit'
    | '/_authenticated/u/$uId/requests/$requestId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/events': {
      id: '/_public/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof PublicEventsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/data': {
      id: '/_public/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof PublicDataRouteImport
      parentRoute: typeof PublicRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/requests': {
      id: '/_public/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof PublicRequestsRouteRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/fund-a-project': {
      id: '/_public/fund-a-project'
      path: '/fund-a-project'
      fullPath: '/fund-a-project'
      preLoaderRoute: typeof PublicFundAProjectRouteRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/requests/': {
      id: '/_public/requests/'
      path: '/'
      fullPath: '/requests/'
      preLoaderRoute: typeof PublicRequestsIndexRouteImport
      parentRoute: typeof PublicRequestsRouteRoute
    }
    '/_public/fund-a-project/': {
      id: '/_public/fund-a-project/'
      path: '/'
      fullPath: '/fund-a-project/'
      preLoaderRoute: typeof PublicFundAProjectIndexRouteImport
      parentRoute: typeof PublicFundAProjectRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/requests/$id': {
      id: '/_public/requests/$id'
      path: '/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof PublicRequestsIdRouteImport
      parentRoute: typeof PublicRequestsRouteRoute
    }
    '/_public/fund-a-project/$id': {
      id: '/_public/fund-a-project/$id'
      path: '/$id'
      fullPath: '/fund-a-project/$id'
      preLoaderRoute: typeof PublicFundAProjectIdRouteImport
      parentRoute: typeof PublicFundAProjectRouteRoute
    }
    '/_public/events/$id': {
      id: '/_public/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof PublicEventsIdRouteImport
      parentRoute: typeof PublicEventsRoute
    }
    '/_authenticated/u/dashboard': {
      id: '/_authenticated/u/dashboard'
      path: '/u/dashboard'
      fullPath: '/u/dashboard'
      preLoaderRoute: typeof AuthenticatedUDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/u/$uId/settings': {
      id: '/_authenticated/u/$uId/settings'
      path: '/u/$uId/settings'
      fullPath: '/u/$uId/settings'
      preLoaderRoute: typeof AuthenticatedUUIdSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/u/$uId/profile': {
      id: '/_authenticated/u/$uId/profile'
      path: '/u/$uId/profile'
      fullPath: '/u/$uId/profile'
      preLoaderRoute: typeof AuthenticatedUUIdProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/u/$uId/fundme': {
      id: '/_authenticated/u/$uId/fundme'
      path: '/u/$uId/fundme'
      fullPath: '/u/$uId/fundme'
      preLoaderRoute: typeof AuthenticatedUUIdFundmeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orgs/$orgId/settings': {
      id: '/_authenticated/orgs/$orgId/settings'
      path: '/orgs/$orgId/settings'
      fullPath: '/orgs/$orgId/settings'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orgs/$orgId/profile': {
      id: '/_authenticated/orgs/$orgId/profile'
      path: '/orgs/$orgId/profile'
      fullPath: '/orgs/$orgId/profile'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orgs/$orgId/members': {
      id: '/_authenticated/orgs/$orgId/members'
      path: '/orgs/$orgId/members'
      fullPath: '/orgs/$orgId/members'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdMembersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orgs/$orgId/events': {
      id: '/_authenticated/orgs/$orgId/events'
      path: '/orgs/$orgId/events'
      fullPath: '/orgs/$orgId/events'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdEventsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orgs/$orgId/dashboard': {
      id: '/_authenticated/orgs/$orgId/dashboard'
      path: '/orgs/$orgId/dashboard'
      fullPath: '/orgs/$orgId/dashboard'
      preLoaderRoute: typeof AuthenticatedOrgsOrgIdDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/u/$uId/tags/': {
      id: '/_authenticated/u/$uId/tags/'
      path: '/u/$uId/tags'
      fullPath: '/u/$uId/tags'
      preLoaderRoute: typeof AuthenticatedUUIdTagsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/u/$uId/profile/': {
      id: '/_authenticated/u/$uId/profile/'
      path: '/'
      fullPath: '/u/$uId/profile/'
      preLoaderRoute: typeof AuthenticatedUUIdProfileIndexRouteImport
      parentRoute: typeof AuthenticatedUUIdProfileRoute
    }
    '/_authenticated/u/$uId/requests/new': {
      id: '/_authenticated/u/$uId/requests/new'
      path: '/u/$uId/requests/new'
      fullPath: '/u/$uId/requests/new'
      preLoaderRoute: typeof AuthenticatedUUIdRequestsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/u/$uId/profile/new': {
      id: '/_authenticated/u/$uId/profile/new'
      path: '/new'
      fullPath: '/u/$uId/profile/new'
      preLoaderRoute: typeof AuthenticatedUUIdProfileNewRouteImport
      parentRoute: typeof AuthenticatedUUIdProfileRoute
    }
    '/_authenticated/u/$uId/profile/edit': {
      id: '/_authenticated/u/$uId/profile/edit'
      path: '/edit'
      fullPath: '/u/$uId/profile/edit'
      preLoaderRoute: typeof AuthenticatedUUIdProfileEditRouteImport
      parentRoute: typeof AuthenticatedUUIdProfileRoute
    }
    '/_authenticated/u/$uId/fund-a-project/new': {
      id: '/_authenticated/u/$uId/fund-a-project/new'
      path: '/u/$uId/fund-a-project/new'
      fullPath: '/u/$uId/fund-a-project/new'
      preLoaderRoute: typeof AuthenticatedUUIdFundAProjectNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/u/$uId/requests/$requestId/edit': {
      id: '/_authenticated/u/$uId/requests/$requestId/edit'
      path: '/u/$uId/requests/$requestId/edit'
      fullPath: '/u/$uId/requests/$requestId/edit'
      preLoaderRoute: typeof AuthenticatedUUIdRequestsRequestIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/u/$uId/fund-a-project/$fundAProjectId/edit': {
      id: '/_authenticated/u/$uId/fund-a-project/$fundAProjectId/edit'
      path: '/u/$uId/fund-a-project/$fundAProjectId/edit'
      fullPath: '/u/$uId/fund-a-project/$fundAProjectId/edit'
      preLoaderRoute: typeof AuthenticatedUUIdFundAProjectFundAProjectIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedUUIdProfileRouteChildren {
  AuthenticatedUUIdProfileEditRoute: typeof AuthenticatedUUIdProfileEditRoute
  AuthenticatedUUIdProfileNewRoute: typeof AuthenticatedUUIdProfileNewRoute
  AuthenticatedUUIdProfileIndexRoute: typeof AuthenticatedUUIdProfileIndexRoute
}

const AuthenticatedUUIdProfileRouteChildren: AuthenticatedUUIdProfileRouteChildren =
  {
    AuthenticatedUUIdProfileEditRoute: AuthenticatedUUIdProfileEditRoute,
    AuthenticatedUUIdProfileNewRoute: AuthenticatedUUIdProfileNewRoute,
    AuthenticatedUUIdProfileIndexRoute: AuthenticatedUUIdProfileIndexRoute,
  }

const AuthenticatedUUIdProfileRouteWithChildren =
  AuthenticatedUUIdProfileRoute._addFileChildren(
    AuthenticatedUUIdProfileRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedUDashboardRoute: typeof AuthenticatedUDashboardRoute
  AuthenticatedOrgsOrgIdDashboardRoute: typeof AuthenticatedOrgsOrgIdDashboardRoute
  AuthenticatedOrgsOrgIdEventsRoute: typeof AuthenticatedOrgsOrgIdEventsRoute
  AuthenticatedOrgsOrgIdMembersRoute: typeof AuthenticatedOrgsOrgIdMembersRoute
  AuthenticatedOrgsOrgIdProfileRoute: typeof AuthenticatedOrgsOrgIdProfileRoute
  AuthenticatedOrgsOrgIdSettingsRoute: typeof AuthenticatedOrgsOrgIdSettingsRoute
  AuthenticatedUUIdFundmeRoute: typeof AuthenticatedUUIdFundmeRoute
  AuthenticatedUUIdProfileRoute: typeof AuthenticatedUUIdProfileRouteWithChildren
  AuthenticatedUUIdSettingsRoute: typeof AuthenticatedUUIdSettingsRoute
  AuthenticatedUUIdFundAProjectNewRoute: typeof AuthenticatedUUIdFundAProjectNewRoute
  AuthenticatedUUIdRequestsNewRoute: typeof AuthenticatedUUIdRequestsNewRoute
  AuthenticatedUUIdTagsIndexRoute: typeof AuthenticatedUUIdTagsIndexRoute
  AuthenticatedUUIdFundAProjectFundAProjectIdEditRoute: typeof AuthenticatedUUIdFundAProjectFundAProjectIdEditRoute
  AuthenticatedUUIdRequestsRequestIdEditRoute: typeof AuthenticatedUUIdRequestsRequestIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedUDashboardRoute: AuthenticatedUDashboardRoute,
  AuthenticatedOrgsOrgIdDashboardRoute: AuthenticatedOrgsOrgIdDashboardRoute,
  AuthenticatedOrgsOrgIdEventsRoute: AuthenticatedOrgsOrgIdEventsRoute,
  AuthenticatedOrgsOrgIdMembersRoute: AuthenticatedOrgsOrgIdMembersRoute,
  AuthenticatedOrgsOrgIdProfileRoute: AuthenticatedOrgsOrgIdProfileRoute,
  AuthenticatedOrgsOrgIdSettingsRoute: AuthenticatedOrgsOrgIdSettingsRoute,
  AuthenticatedUUIdFundmeRoute: AuthenticatedUUIdFundmeRoute,
  AuthenticatedUUIdProfileRoute: AuthenticatedUUIdProfileRouteWithChildren,
  AuthenticatedUUIdSettingsRoute: AuthenticatedUUIdSettingsRoute,
  AuthenticatedUUIdFundAProjectNewRoute: AuthenticatedUUIdFundAProjectNewRoute,
  AuthenticatedUUIdRequestsNewRoute: AuthenticatedUUIdRequestsNewRoute,
  AuthenticatedUUIdTagsIndexRoute: AuthenticatedUUIdTagsIndexRoute,
  AuthenticatedUUIdFundAProjectFundAProjectIdEditRoute:
    AuthenticatedUUIdFundAProjectFundAProjectIdEditRoute,
  AuthenticatedUUIdRequestsRequestIdEditRoute:
    AuthenticatedUUIdRequestsRequestIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicFundAProjectRouteRouteChildren {
  PublicFundAProjectIdRoute: typeof PublicFundAProjectIdRoute
  PublicFundAProjectIndexRoute: typeof PublicFundAProjectIndexRoute
}

const PublicFundAProjectRouteRouteChildren: PublicFundAProjectRouteRouteChildren =
  {
    PublicFundAProjectIdRoute: PublicFundAProjectIdRoute,
    PublicFundAProjectIndexRoute: PublicFundAProjectIndexRoute,
  }

const PublicFundAProjectRouteRouteWithChildren =
  PublicFundAProjectRouteRoute._addFileChildren(
    PublicFundAProjectRouteRouteChildren,
  )

interface PublicRequestsRouteRouteChildren {
  PublicRequestsIdRoute: typeof PublicRequestsIdRoute
  PublicRequestsIndexRoute: typeof PublicRequestsIndexRoute
}

const PublicRequestsRouteRouteChildren: PublicRequestsRouteRouteChildren = {
  PublicRequestsIdRoute: PublicRequestsIdRoute,
  PublicRequestsIndexRoute: PublicRequestsIndexRoute,
}

const PublicRequestsRouteRouteWithChildren =
  PublicRequestsRouteRoute._addFileChildren(PublicRequestsRouteRouteChildren)

interface PublicEventsRouteChildren {
  PublicEventsIdRoute: typeof PublicEventsIdRoute
}

const PublicEventsRouteChildren: PublicEventsRouteChildren = {
  PublicEventsIdRoute: PublicEventsIdRoute,
}

const PublicEventsRouteWithChildren = PublicEventsRoute._addFileChildren(
  PublicEventsRouteChildren,
)

interface PublicRouteChildren {
  PublicFundAProjectRouteRoute: typeof PublicFundAProjectRouteRouteWithChildren
  PublicRequestsRouteRoute: typeof PublicRequestsRouteRouteWithChildren
  PublicDataRoute: typeof PublicDataRoute
  PublicEventsRoute: typeof PublicEventsRouteWithChildren
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicFundAProjectRouteRoute: PublicFundAProjectRouteRouteWithChildren,
  PublicRequestsRouteRoute: PublicRequestsRouteRouteWithChildren,
  PublicDataRoute: PublicDataRoute,
  PublicEventsRoute: PublicEventsRouteWithChildren,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
